<?php
/* THIS IS A GENERATED FILE. DO NOT EDIT DIRECTLY. */
$wp_starter_i18n_strings = array(
	__( 'Recommended', 'siteground-wizard' ),
	__( 'Add', 'siteground-wizard' ),
	__( 'Added', 'siteground-wizard' ),
	__( '{{free}}Free{{/free}} plugin {{by}}by %(author)s{{/by}}', 'siteground-wizard' ),
	__( 'CLOSE', 'siteground-wizard' ),
	__( 'Active', 'siteground-wizard' ),
	__( 'Active', 'siteground-wizard' ),
	__( 'LATEST VERSION INSTALLED', 'siteground-wizard' ),
	__( 'Sorry, could not install theme', 'siteground-wizard' ),
	__( 'Sorry, could not install theme', 'siteground-wizard' ),
	__( 'Live Preview', 'siteground-wizard' ),
	__( "Installing, please don't close or refresh this page.", 'siteground-wizard' ),
	__( 'Installation in progress...', 'siteground-wizard' ),
	__( 'WordPress Starter', 'siteground-wizard' ),
	__( 'EXIT', 'siteground-wizard' ),
	__( 'EXIT WIZARD', 'siteground-wizard' ),
	__( 'Congrats! Your site is ready!', 'siteground-wizard' ),
	__( 'Close', 'siteground-wizard' ),
	__( 'View Site', 'siteground-wizard' ),
	__( 'We have successfully completed the installation of the items you selected. You may now proceed to your WordPress dashboard and start managing your site.', 'siteground-wizard' ),
	__( 'Sorry, could not install theme', 'siteground-wizard' ),
	__( 'Sorry, could not install theme', 'siteground-wizard' ),
	__( 'WooCommerce', 'siteground-wizard' ),
	__( 'WooCommerce empowers millions of shops and is full of features that allow you to manage diverse products.', 'siteground-wizard' ),
	__( 'Free', 'siteground-wizard' ),
	__( 'plugin by Automattic', 'siteground-wizard' ),
	__( 'Sorry, there was an unexpected problem.', 'siteground-wizard' ),
	__( 'Error', 'siteground-wizard' ),
	__( 'Success', 'siteground-wizard' ),
	__( 'Theme search', 'siteground-wizard' ),
	__( 'Select', 'siteground-wizard' ),
	__( 'ALL', 'siteground-wizard' ),
	__( 'Other', 'siteground-wizard' ),
	__( 'ALL', 'siteground-wizard' ),
	__( 'Online-store', 'siteground-wizard' ),
	__( 'ALL', 'siteground-wizard' ),
	__( 'selected', 'siteground-wizard' ),
	__( 'select', 'siteground-wizard' ),
	__( 'selected', 'siteground-wizard' ),
	__( 'select', 'siteground-wizard' ),
	__( 'CLOSE', 'siteground-wizard' ),
	__( 'SELECT', 'siteground-wizard' ),
	__( 'Error', 'siteground-wizard' ),
	__( 'Success', 'siteground-wizard' ),
	__( 'Dashboard', 'siteground-wizard' ),
	__( 'you', 'siteground-wizard' ),
	__( 'Attend an upcoming event near %(city)s', 'siteground-wizard' ),
	__( 'City', 'siteground-wizard' ),
	__( 'Submit', 'siteground-wizard' ),
	__( 'Cancel', 'siteground-wizard' ),
	__( 'Learn more', 'siteground-wizard' ),
	__( 'Activate', 'siteground-wizard' ),
	__( 'Active', 'siteground-wizard' ),
	__( 'Add Plugins', 'siteground-wizard' ),
	__( 'Search By', 'siteground-wizard' ),
	__( 'Search', 'siteground-wizard' ),
	__( 'Search plugins...', 'siteground-wizard' ),
	__( 'Search', 'siteground-wizard' ),
	__( 'Learn more', 'siteground-wizard' ),
	__( 'Activate', 'siteground-wizard' ),
	__( 'Active', 'siteground-wizard' ),
	__( 'You are updating a plugin. Be sure to back up your database and files first.', 'siteground-wizard' ),
	__( 'Load More', 'siteground-wizard' ),
	__( 'You are updating a theme. Be sure to back up your database and files first.', 'siteground-wizard' ),
	__( 'Add Themes', 'siteground-wizard' ),
	__( 'Search By', 'siteground-wizard' ),
	__( 'Search', 'siteground-wizard' ),
	__( 'Search themes...', 'siteground-wizard' ),
	__( 'Search', 'siteground-wizard' ),
	__( 'Live Preview', 'siteground-wizard' ),
	__( 'Load More', 'siteground-wizard' ),
);
/* THIS IS THE END OF THE GENERATED FILE */